delete from [LoginService].[InvalidPasswords]

insert into [LoginService].[InvalidPasswords] values (NEWID(),'year')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'   ')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'aaa')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'bbb')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'ccc')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'ddd')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'eee')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'fff')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'hhh')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'iii')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'jjj')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'kkk')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'lll')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'mmm')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'nnn')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'ooo')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'ppp')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'qqq')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'rrr')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'sss')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'ttt')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'uuu')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'vvv')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'xxx')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'yyy')
insert into [LoginService].[InvalidPasswords] values (NEWID(),'zzz')

INSERT INTO [LoginService].[InvalidPasswords]  ([Password]) VALUES
(N'!"£$'),
(N'!QAZ1qaz'),
(N'!qaz2wsx'),
(N'!qazxsw2'),
(N'!qazzaq'),
(N'000'),
(N'111'),
(N'222'),
(N'333'),
(N'444'),
(N'555'),
(N'666'),
(N'777'),
(N'888'),
(N'999'),
(N'1st'),
(N'2nd'),
(N'3rd'),
(N'4th'),
(N'5th'),
(N'6th'),
(N'7th'),
(N'8th'),
(N'9th'),
(N'0th'),
(N'1234'),
(N'2345'),
(N'3456'),
(N'4567'),
(N'5678'),
(N'6789'),
(N'7890'),
(N'10fingers'),
(N'10inches'),
(N'10million'),
(N'11aa22bb'),
(N'11eleven'),
(N'11qq11qq'),
(N'11qq22ww'),
(N'11qqaazz'),
(N'12inches'),
(N'12q12q12q'),
(N'12qazwsx'),
(N'12qw12qw'),
(N'12qw23we'),
(N'12qw34as'),
(N'12qw34er'),
(N'12qwasyx'),
(N'12qwaszx'),
(N'12s3t4p55'),
(N'12stones'),
(N'13thirteen'),
(N'18wheeler'),
(N'55chevy'),
(N'57chevy'),
(N'1a2a3a4a'),
(N'1a2b3c4d'),
(N'1a2s3d4f'),
(N'1abcdefg'),
(N'1andonly'),
(N'bastard'),
(N'bigcock'),
(N'bigdaddy'),
(N'bigdick'),
(N'bigfish'),
(N'bighead'),
(N'bigpimp'),
(N'1billion'),
(N'1q2q3q4q'),
(N'1q2w1q2w'),
(N'1q2w3e1q2w3e'),
(N'1q2w3e4r'),
(N'1q2w3easd'),
(N'1q3e2w4r'),
(N'1q3e5t7u'),
(N'1qa2ws3e'),
(N'1qasw23ed'),
(N'1qay2wsx'),
(N'1qayxsw2'),
(N'1qaz!QAZ'),
(N'1qaz@WSX'),
(N'1qaz0okm'),
(N'1qaz1qaz'),
(N'1qaz2wsx'),
(N'1qaz3edc'),
(N'1qazwsxedc'),
(N'1qazxdr5'),
(N'1qazxsw@'),
(N'1qazxsw2'),
(N'1qazzaq'),
(N'1qw21qw2'),
(N'1qw23er4'),
(N'1qweasdzxc'),
(N'qwerty'),
(N'1z2x3c4v'),
(N'3sisters'),
(N'3stooges'),
(N'44magnum'),
(N'4ever'),
(N'50cent'),
(N'63impala'),
(N'64impala'),
(N'65impala'),
(N'65mustang'),
(N'66cheve'),
(N'66mustang'),
(N'67camaro'),
(N'67cheve'),
(N'67mustang'),
(N'67shelby'),
(N'68camaro'),
(N'68charger'),
(N'68cheve'),
(N'68mustang'),
(N'69camaro'),
(N'69charger'),
(N'69cheve'),
(N'69cougar'),
(N'69mustang'),
(N'6shooter'),
(N'6strings'),
(N'70cheve'),
(N'71cheve'),
(N'72cheve'),
(N'79camaro'),
(N'79transam'),
(N'7samurai'),
(N'88mustang'),
(N'89mustang'),
(N'911turbo'),
(N'91camaro'),
(N'91mustang'),
(N'92camaro'),
(N'93mustang'),
(N'94mustang'),
(N'95camaro'),
(N'95mustang'),
(N'96impala'),
(N'96mustang'),
(N'98mustang'),
(N'99bottles'),
(N'99mustang'),
(N'99problems'),
(N'9inchnails'),
(N'a11223344'),
(N'a12121212'),
(N'a12b13c14'),
(N'a1a1a1a'),
(N'a1a2a3a4'),
(N'a1b1c1d1'),
(N'a1b2c3d4'),
(N'a2a2a2a2'),
(N'abuse'),
(N'access'),
(N'admin'),
(N'as123123'),
(N'as12as12'),
(N'as12df34'),
(N'asas1122'),
(N'asas1212'),
(N'asasas12'),
(N'asdfg'),
(N'b0ll0cks'),
(N'b1b2b3b4'),
(N'beckham'),
(N'blahblah'),
(N'bond007'),
(N'br00klyn'),
(N'bradpitt'),
(N'bugatti'),
(N'c0cac0la'),
(N'c0mput3r'),
(N'c0mputer'),
(N'carrera'),
(N'cerveza'),
(N'ch0c0late'),
(N'chevel'),
(N'choochoo'),
(N'chouchou'),
(N'chowchow'),
(N'ciaociao'),
(N'copyright'),
(N'iphone'),
(N'ipod'),
(N'keyboard'),
(N'komputer'),
(N'l0llip0p'),
(N'l0vel0ve'),
(N'l1nk3d1n'),
(N'l1nked1n'),
(N'l1o2v3e4'),
(N'l1v3rp00l'),
(N'l1verp00l'),
(N'l1verpool'),
(N'ladder49'),
(N'laptop'),
(N'laracroft'),
(N'live2'),
(N'live4'),
(N'livelife'),
(N'livelove'),
(N'liverp00l'),
(N'liverpool'),
(N'livewire'),
(N'lockdown'),
(N'm1i2k3e4'),
(N'm1m2m3m4'),
(N'mp3player'),
(N'number'),
(N'numb3r'),
(N'o0o0o'),
(N'omgomg'),
(N'one1'),
(N'two2'),
(N'only1'),
(N'ssword'),
(N'ssw0rd'),
(N'$$word'),
(N'$$w0rd'),
(N'5$word'),
(N'$5w0rd'),
(N's$word'),
(N'$sw0rd'),
(N's5word'),
(N's5w0rd'),
(N'5sword'),
(N'5sw0rd'),
(N'55word'),
(N'55w0rd'),
(N'zzword'),
(N'zzw0rd'),
(N'z5word'),
(N'z5w0rd'),
(N'5zword'),
(N'5zw0rd'),
(N'asswrd'),
(N'as5wrd'),
(N'a5swrd'),
(N'a55wrd'),
(N'4sswrd'),
(N'4s5wrd'),
(N'45swrd'),
(N'455wrd'),
(N'4$swrd'),
(N'4$5wrd'),
(N'45$wrd'),
(N'4s$wrd'),
(N'p1p2p3p4'),
(N'paspas'),
(N'pentium'),
(N'q123q123'),
(N'q12we34r'),
(N'q1q1q1q'),
(N'q1q2q3q4'),
(N'q1w2e3r4'),
(N'q1w2q1w2'),
(N'qawsed12'),
(N'qawsedrf'),
(N'qaywsx123'),
(N'qw12332'),
(N'qw12er34'),
(N'qw12qw12'),
(N'qwaszx1'),
(N'qweqwe'),
(N'qwqw1212'),
(N'qwqwqw12'),
(N'r1r2r3r4'),
(N'r2d2c3p0'),
(N'r2d2c3po'),
(N'r2d2r2d2'),
(N'remember'),
(N'rem3mber'),
(N'rememb3r'),
(N'r3member'),
(N'r3m3mber'),
(N'r3memb3r'),
(N'r3m3mb3r'),
(N'r4e3w2q'),
(N's1s2s3s4'),
(N's1t2o3n4'),
(N'sh0pping'),
(N'shopping'),
(N'sh1thead'),
(N'slipkn0t'),
(N'slipknot'),
(N'sp0ngeb0b'),
(N'spongebob'),
(N'sp1derman'),
(N'spongbob'),
(N'system'),
(N'unique'),
(N'w0rdpass'),
(N'w1w2w3w4'),
(N'w2e3r4t5'),
(N'welcome'),
(N'what3v3r'),
(N'whateva'),
(N'whatever'),
(N'whatitdo'),
(N'whatnow'),
(N'whatsup'),
(N'whatthe'),
(N'whatwhat'),
(N'whoareyou'),
(N'whocares'),
(N'windows'),
(N'w1ndows'),
(N'wind0ws'),
(N'w1nd0ws'),
(N'z1x1c1v'),
(N'z1x2c3v4'),
(N'z1z1z1z'),
(N'z1z2z3z4'),
(N'zero0'),
(N'zxcv')
GO




































